# 389. Find the Difference
# Solved
# Easy
# Topics
# premium lock icon
# Companies
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        counts = {}
        
        for char in s:
            if char in counts:
                counts[char] += 1
            else:
                counts[char] = 1
        
        for char in t:
            if char not in counts or counts[char] == 0:
                return char
            else:
                counts[char] -= 1
        
        return ""